pom.xml
following Maven guide https://maven.apache.org/guides/mini/guide-reproducible-builds.html
only added timestamp to go to Reproducible Builds mode, and upgraded maven-release-plugin to have the timestamp automatically updated on release
=> make build Reproducible

src/main/java/io/micronaut/build/RunMojo.java, src/site/asciidoc/examples/run.adoc
Add a parameter to specify the debugger host.
Example: `mvn mn:run -Dmn.debug -Dmn.debug.host=192.168.1.8` or `mvn mn:run -Dmn.debug -Dmn.debug.host=*`
Closes #84
=> feat: add mn.debug.host parameter to mn:run command

src/it/dockerfile-docker-native-netty/Dockerfile, src/main/resources/dockerfiles/DockerfileNative
The `latest` version of `frolvlad/alpine-glibc` (3.13) is not compatible with GraalVM and application fail with a segmentation fault. This PR sets the version to the previous one that works (3.12)
More info: https://github.com/oracle/graal/issues/3159
=> Use alpine-glibc:3.12 as base image

src/main/java/io/micronaut/build/jib/JibMicronautExtension.java
If the port in the application config is an expression like `"${FOO_BAR:8090}"` then the plugin fails 
with an exception like:
```
error running extension 'io.micronaut.build.jib.JibMicronautExtension': extension crashed: For input string: "${FOO_BAR:8090}" -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.google.cloud.tools:jib-maven-plugin:2.7.1:dockerBuild (default-dockerBuild)
```
This PR resolves that by catching the exception and suggesting configuring the exposed port manually
=> Fix case where port is defined as an expression

src/it/dockerfile-docker-native-lambda/pom.xml, src/it/dockerfile-docker-native-netty/pom.xml, src/it/dockerfile-docker-native-oracle-function/pom.xml, src/it/package-native-image/pom.xml
This fixes the broken tests after the upgrade to GraalVM 21.1.0. See https://github.com/micronaut-projects/micronaut-maven-plugin/commit/5e2b3398b85c879cff235cbb041b8172f0adc36f
=> Set specific GraalVM version for tests to avoid getting it from Micronaut BOM

pom.xml, src/it/package-docker-native/verify.groovy, src/it/package-native-image/openapi.properties, src/it/package-native-image/pom.xml, src/it/package-native-image/src/main/java/io/micronaut/build/examples/Application.java, src/it/package-native-image/verify.groovy, src/main/java/io/micronaut/build/GraalVMResourcesMojo.java, src/main/resources/META-INF/plexus/components.xml
This PR adds a new goal that is executed automatically and that creates the GraalVM `resource-config.json` automatically.
This needs to target Micronaut 3.0.x and be merged with the same [PR for Gradle plugin](https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/215)
=> New goal (executed automatically) to generate GraalVM resources file

src/main/java/io/micronaut/build/DockerMojo.java
Currently, system property `jib.from.image` is always set to the value of `JibMicronautExtension.DEFAULT_BASE_IMAGE`.
The jib-maven-plugin will always pick this image regardless of what `<from><image>` plugin configuration is set to.
This fix changes the default behavior to only set `jib.from.image` to default image if `<from><image>` is not set in the jib-maven-plugin configuration.
See also: https://github.com/micronaut-projects/micronaut-maven-plugin/issues/178
=> Honor from.image if defined in jib-maven-plugin configuration #178

src/it/dockerfile-docker-native-distroless/Dockerfile, src/it/dockerfile-docker-native-distroless/pom.xml, src/it/dockerfile-docker-native-lambda/Dockerfile, src/it/dockerfile-docker-native-lambda/pom.xml, src/it/dockerfile-docker-native-netty/Dockerfile, src/it/dockerfile-docker-native-netty/pom.xml, src/it/dockerfile-docker-native-oracle-function/Dockerfile, src/it/dockerfile-docker-native-oracle-function/pom.xml, src/it/dockerfile-docker-native-static/Dockerfile, src/it/dockerfile-docker-native-static/pom.xml, src/it/package-docker-native-distroless/pom.xml, src/it/package-docker-native-static/Dockerfile, src/it/package-docker-native-static/pom.xml, src/it/package-docker-native/pom.xml, src/it/package-native-image/pom.xml, src/main/java/io/micronaut/build/AbstractDockerMojo.java
Fixes #272 as currently native images fail to build as the default base images do not exist.
=> Fix #272 - GraalVM image names are invalid

src/main/java/io/micronaut/build/RunMojo.java, src/main/java/io/micronaut/build/aot/AbstractMicronautAotMojo.java
This PR:
* Cleans the AOT output directory before running AOT.
* Removes the initial compilation in `mn:run`. It is no longer needed because since version 3.2.0, the run mojo forks the `process-classes` phase, which includes `compile`.
=> Fix AOT execution

src/main/java/io/micronaut/build/aot/AbstractMicronautAotMojo.java, src/main/java/io/micronaut/build/aot/AotAnalysisMojo.java
Since it can contain an AOT-generated class for a different runtime than the current execution.
Fixes #329.
=> Clean target/classes before running AOT

examples/java/pom.xml, src/it/test-resources-custom-dependency/pom.xml, src/it/test-resources-disabled/invoker.properties, src/it/test-resources-disabled/pom.xml, src/it/test-resources-disabled/src/main/java/io/micronaut/build/examples/Application.java, src/it/test-resources-disabled/src/main/resources/application.yml, src/it/test-resources-disabled/src/main/resources/logback.xml, src/it/test-resources-disabled/verify.groovy, src/it/test-resources-failing-test/pom.xml, src/main/java/io/micronaut/build/services/DependencyResolutionService.java, src/main/java/io/micronaut/build/testresources/AbstractTestResourcesMojo.java, src/main/java/io/micronaut/build/testresources/StopTestResourcesHelper.java, src/main/java/io/micronaut/build/testresources/StopTestResourcesServerMojo.java, src/main/java/io/micronaut/build/testresources/TestResourcesLifecycleExtension.java, src/site/asciidoc/examples/test-resources.adoc
This adds `io.micronaut.testresources:micronaut-test-resources-client`
as a `test` dependency if Test Resources is enabled.
It also uses a proper expression evaluation mechanism.
=> Add Test Resources client dependency automatically

src/main/java/io/micronaut/build/DockerCracMojo.java, src/main/java/io/micronaut/build/services/DockerService.java
If using mysql in a container, we need to be able to specify the network it is running on.
=> Allow setting a network for the crac checkpoint

.github/renovate.json, examples/java/Dockerfile.example, micronaut-maven-integration-tests/src/it/dockerfile-docker-lambda/Dockerfile, micronaut-maven-integration-tests/src/it/dockerfile-docker-netty/Dockerfile, micronaut-maven-jib-integration/src/main/java/io/micronaut/maven/jib/JibMicronautExtension.java, micronaut-maven-plugin/src/main/resources/dockerfiles/Dockerfile
The `openjdk` project has been deprecated and only publishes early access
builds[1]. As a result the `openjdk:17-alpine` on Dockerhub has not been
updated in the last year and a half.
Replacing the image with `eclipse-temurin` should resolve these issues. The
choice for `eclipse-temurin` is somewhat arbitrary. But as an opensource
project its good enough.
1. https://hub.docker.com/_/openjdk
Fixes: #628
=> Replace openjdk with eclipse-temurin

micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty-custom-ol/Dockerfile, micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty-custom-ol/invoker.properties, micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty-custom-ol/pom.xml, micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty-custom-ol/src/main/java/io/micronaut/build/examples/Application.java, micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty-custom-ol/src/main/java/io/micronaut/build/examples/greeter/Greeter.java, micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty-custom-ol/src/main/resources/application.yml, micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty-custom-ol/src/main/resources/logback.xml, micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty-custom-ol/src/test/java/io/micronaut/build/examples/ApplicationTest.java, micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty-custom-ol/verify.groovy, micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty/Dockerfile, micronaut-maven-integration-tests/src/it/dockerfile-docker-native-oracle-function/Dockerfile, micronaut-maven-integration-tests/src/it/dockerfile-docker-native-static/Dockerfile, micronaut-maven-integration-tests/src/it/package-docker-native-static/Dockerfile, micronaut-maven-plugin/src/main/java/io/micronaut/maven/AbstractDockerMojo.java
Defaults to ol8, but can be configured via graal.oracle.linux.version
This is to align it with https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/714
=> Allow setting OracleLinux version for native base image

micronaut-maven-jib-integration/src/main/java/io/micronaut/maven/jib/JibMicronautExtension.java
Logical error on line 55 in JibMicronautExtension#ContainerBuildPlan
```
if (StringUtils.isNotEmpty(buildPlan.getBaseImage())) {
builder.setBaseImage(DEFAULT_BASE_IMAGE);
}
```
Changed to
```
if (StringUtils.isEmpty(buildPlan.getBaseImage())) {
builder.setBaseImage(DEFAULT_BASE_IMAGE);
}
```
=> StringUtils.isNotEmpty -> StringUtils.isEmpty

micronaut-maven-integration-tests/pom.xml, micronaut-maven-integration-tests/src/it/run-aot/pom.xml, micronaut-maven-integration-tests/src/it/test-resources-custom-dependency/pom.xml, micronaut-maven-integration-tests/src/it/test-resources-failing-test/pom.xml, micronaut-maven-integration-tests/src/it/test-resources-shared-namespace/pom.xml, micronaut-maven-integration-tests/src/it/test-resources-shared/pom.xml, micronaut-maven-integration-tests/src/it/test-resources-start-stop/pom.xml, micronaut-maven-integration-tests/src/it/test-resources/pom.xml, micronaut-maven-plugin/pom.xml, micronaut-maven-plugin/src/main/java/io/micronaut/maven/testresources/DefaultServerFactory.java, micronaut-maven-plugin/src/main/java/io/micronaut/maven/testresources/TestResourcesHelper.java, micronaut-maven-plugin/src/main/java/io/micronaut/maven/testresources/TestResourcesLifecycleExtension.java, pom.xml
This PR upgrades the Test Resources support to use M10, which no longer supports reading properties from classpath, but instead, will read from system properties or a couple of default file system locations.
It also stops adding the client dependency under the covers (which was a hack), so it needs a counterpart PR in Starter.
=> Upgrade to Test Resources M10

micronaut-maven-plugin/src/main/java/io/micronaut/maven/DockerNativeMojo.java
Parent’s coordinate has changed from:
```
<parent>
<groupId>io.micronaut</groupId>
<artifactId>micronaut-parent</artifactId>
```
to: 
```
<parent>
<groupId>io.micronaut.platform</groupId>
<artifactId>micronaut-parent</artifactId>
```
Close: https://github.com/micronaut-projects/micronaut-maven-plugin/issues/791
=> update micronaut-parent coordinates

micronaut-maven-integration-tests/src/it/dockerfile-docker-native-static/Dockerfile, micronaut-maven-integration-tests/src/it/package-docker-native-static/Dockerfile, micronaut-maven-plugin/src/main/resources/dockerfiles/DockerfileNativeStatic
Zlib removed the 1.2.13 distribution when they released 1.3 on 18 August 2023.
Although 1.2.13 [appears to be available from GitHub](https://github.com/madler/zlib/releases/tag/v1.2.13), this PR attempts to upgrade to 1.3
=> Upgrade Zlib to 1.3

src/it/dockerfile-docker-crac/Dockerfile.crac.checkpoint, src/main/resources/dockerfiles/DockerfileCracCheckpoint
Azul added a JRE to their CRaC java deliverables.
The query wasn't specific enough to say we want a JDK, so we end up pulling the JRE if it comes back first in the response.
This change adds java_package_type=jdk to the request URL so we just get the JDK.
=> Fix CRaC JDK download in docker container

micronaut-maven-plugin/src/main/java/io/micronaut/maven/DockerNativeMojo.java, pom.xml
=> Fix latest version of Native Build Tools

README.md, micronaut-maven-plugin/src/main/java/io/micronaut/maven/testresources/TestResourcesHelper.java
This commit fixes the fact that the test resources service could be kept alive even when invoking `mn:stop-testresources-service`. This was caused by the presence of a stale keepalive file. The scenario to trigger this was:
1. execute `mvn mn:start-testresources-service`
2. execute `mvn run`
3. when the Micronaut server is running, interrupt with CTRL+C
4. execute `mvn mn:stop-testresources-service`
In that case the server was kept alive because the keepalive file was not deleted.
=> Fix test resources service not being shutdown

micronaut-maven-plugin/src/main/java/io/micronaut/maven/RunMojo.java, micronaut-maven-plugin/src/main/java/io/micronaut/maven/testresources/DefaultServerFactory.java, micronaut-maven-plugin/src/main/java/io/micronaut/maven/testresources/StartTestResourcesServerMojo.java, micronaut-maven-plugin/src/main/java/io/micronaut/maven/testresources/StopTestResourcesServerMojo.java, micronaut-maven-plugin/src/main/java/io/micronaut/maven/testresources/TestResourcesConfiguration.java, micronaut-maven-plugin/src/main/java/io/micronaut/maven/testresources/TestResourcesHelper.java, micronaut-maven-plugin/src/main/java/io/micronaut/maven/testresources/TestResourcesLifecycleExtension.java
This commit fixes the logic for shutting down the test resources service. Before, the "keepAlive" flag was exposed to the user. If it was set to true, then invoking `stop-testresources-service` would always keep the service alive. Now, the flag is purely internal and used to keep track of whether the service was _already_ alive before starting the build or not.
The keepalive file is now kept under the temporary directory: this prevents the file from being accidentally deleted by another process, or even conflicts with different namespaces for shared services.
If the service was alive before running the build, it will be kept alive unless `stop-testresources-service` is called. If it wasn't alive, then it will be shutdown at the end of the build.
The logic is now similar to what the Gradle …
=> Fix test resources service keepalive

micronaut-maven-plugin/src/main/java/io/micronaut/maven/RunMojo.java
If the directory passed as `<directory>` was a relative directory (which should always be the case), then the matching would fail with a cryptic error:
`java.lang.IllegalArgumentException: 'other' is different type of Path`
This commit fixes the problem by making sure to convert the directory to an absolute path before performing the path relativization.
=> Fix file watches property

micronaut-maven-plugin/pom.xml, micronaut-maven-plugin/src/main/java/io/micronaut/maven/RunMojo.java, micronaut-maven-plugin/src/test/java/io/micronaut/maven/FileWatchingTest.java
This commit reworks the file watching strategy, in order to make it easier to understand and to fix some bugs. In particular, the previous logic was broken in the context of multiproject builds, depending on whether the build was started from the root project, or from a submodule. It was for example possible that the whole project directory was watched, and not just the default sources and resources directories.
With this change, we removed the separate logic which existed for whether the user had defined watches or not, to replace it with a unified version. Tests were added to make sure that it's possible to watch changes in both single projects and multi-projects.
=> Fix file watching

micronaut-maven-integration-tests/src/it/dockerfile-docker-native-lambda/Dockerfile.aarch64, micronaut-maven-integration-tests/src/it/dockerfile-docker-native-lambda/Dockerfile.amd64, micronaut-maven-plugin/src/main/resources/dockerfiles/DockerfileNativeLambda, micronaut-maven-plugin/src/site/asciidoc/examples/package.adoc
see: https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/929
=> Upgrade `amazonlinux:2` to `amazonlinux:2023`

.mvn/extensions.xml
Updating the common custom user data maven extension to 1.13, which adds the `CI provider` custom value. 
The update is needed manually, as renovate doesn't support managing maven extensions (yet). See issue https://github.com/renovatebot/renovate/issues/24328.
=> Update CCUD Maven extension to 1.13

micronaut-maven-integration-tests/src/it/import-factory-disabled/invoker.properties, micronaut-maven-integration-tests/src/it/import-factory-disabled/pom.xml, micronaut-maven-integration-tests/src/it/import-factory-disabled/src/main/java/io/micronaut/build/examples/Application.java, micronaut-maven-integration-tests/src/it/import-factory-disabled/src/main/resources/application.yml, micronaut-maven-integration-tests/src/it/import-factory-disabled/src/main/resources/logback.xml, micronaut-maven-integration-tests/src/it/import-factory-disabled/src/test/java/io/micronaut/build/examples/ImportFactoryDisabledTest.java, micronaut-maven-integration-tests/src/it/import-factory-disabled/verify.groovy, micronaut-maven-integration-tests/src/it/import-factory-enabled/invoker.properties, micronaut-maven-integration-tests/src/it/import-factory-enabled/pom.xml, micronaut-maven-integration-tests/src/it/import-factory-enabled/src/main/java/io/micronaut/build/examples/Application.java, micronaut-maven-integration-tests/src/it/import-factory-enabled/src/main/resources/application.yml, micronaut-maven-integration-tests/src/it/import-factory-enabled/src/main/resources/logback.xml, micronaut-maven-integration-tests/src/it/import-factory-enabled/src/test/java/io/micronaut/build/examples/ImportFactoryEnabledTest.java, micronaut-maven-integration-tests/src/it/import-factory-enabled/verify.groovy, micronaut-maven-plugin/src/main/java/io/micronaut/maven/ImportFactoryMojo.java, micronaut-maven-plugin/src/main/resources/META-INF/plexus/components.xml, micronaut-maven-plugin/src/site/asciidoc/examples/bean-import.adoc, micronaut-maven-plugin/src/site/asciidoc/index.adoc, micronaut-maven-plugin/src/site/site.xml
Importing beans from dependencies which don't contain Micronaut bean definition classes can be cumbersome, it requires all the packages to be known upfront.
By generating a factory class with the `@Import` annotation for selected packages changes to the packages in dependencies are automatically handled.
See https://github.com/codegen-io/micronaut-import-plugin
Fixes https://github.com/micronaut-projects/micronaut-maven-plugin/issues/1021
=> feat: simplify importing beans from project dependencies

.github/dependabot.yml
Added dependabot config for com.gradle maven extensions as renovate doesn't support updating `extensions.xml` - https://github.com/renovatebot/renovate/issues/24328
=> Added dependabot config for com.gradle maven extensions

micronaut-maven-core/pom.xml, micronaut-maven-enforcer-rules/pom.xml, micronaut-maven-integration-tests/pom.xml, micronaut-maven-integration-tests/src/it/openapi-generate-client/verify.groovy, micronaut-maven-integration-tests/src/it/package-docker-crac-aot/pom.xml, micronaut-maven-jib-integration/pom.xml, micronaut-maven-plugin/pom.xml, pom.xml
In 6.7.0 a the base-url property was renamed to have a dot separator instead of hyphen.
https://github.com/micronaut-projects/micronaut-openapi/pull/1467
We are doing this in a patch release as it is an ongoing bug in Micronaut 4.4.0 and will be released with 4.4.1.
=> Update openapi version to 6.7.0
