micronaut-projects/micronaut-maven-plugin

- src/site/asciidoc/release-history.adoc
- src/site/site.xml
> Add Release History page

- src/main/resources/dockerfiles/DockerfileNative
- src/main/resources/dockerfiles/DockerfileNativeStatic
It will be done by default: https://github.com/micronaut-projects/micronaut-core/pull/4459
> Remove `--install-exit-handlers`

- examples/java/pom.xml
- pom.xml
- src/main/java/io/micronaut/build/DockerNativeMojo.java
- src/main/java/io/micronaut/build/DockerPushMojo.java
- src/main/java/io/micronaut/build/services/JibConfigurationService.java
- src/main/resources/META-INF/plexus/components.xml
- src/site/asciidoc/examples/deploy.adoc
- src/site/asciidoc/index.adoc
> Implement custom `deploy` lifecycle

- src/main/java/io/micronaut/build/AbstractDockerMojo.java
- src/main/java/io/micronaut/build/DockerNativeMojo.java
- src/main/java/io/micronaut/build/DockerfileMojo.java
- src/site/asciidoc/examples/package.adoc
> Documentation fixes

- examples/java/pom.xml
- src/main/java/io/micronaut/build/AbstractDockerMojo.java
- src/main/java/io/micronaut/build/DockerMojo.java
- src/main/java/io/micronaut/build/DockerNativeMojo.java
- src/main/java/io/micronaut/build/DockerfileMojo.java
- src/main/java/io/micronaut/build/RunMojo.java
- src/main/java/io/micronaut/build/jib/JibMicronautExtension.java
- src/main/java/io/micronaut/build/services/ApplicationConfigurationService.java
- src/main/java/io/micronaut/build/services/DockerService.java
- src/main/java/io/micronaut/build/services/JibConfigurationService.java
- src/site/asciidoc/examples/deploy.adoc
- src/site/asciidoc/examples/package.adoc
> Support for Jib configuration properties

- examples/java/pom.xml
- pom.xml
- src/it/deploy/invoker.properties
- src/it/deploy/pom.xml
- src/it/deploy/selector.groovy
- src/it/deploy/src/main/java/io/micronaut/build/examples/Application.java
- src/it/deploy/src/main/java/io/micronaut/build/examples/greeter/Greeter.java
- src/it/deploy/src/main/resources/application.yml
- src/it/deploy/src/main/resources/logback.xml
- src/it/deploy/src/test/java/io/micronaut/build/examples/ApplicationTest.java
- src/it/deploy/verify.groovy
- src/it/package-docker-native/pom.xml
- src/it/package-docker/pom.xml
- src/it/package-jar/pom.xml
- src/it/package-native-image/pom.xml
- src/it/run/pom.xml
- src/main/java/io/micronaut/build/DockerMojo.java
- src/main/java/io/micronaut/build/DockerPushMojo.java
- src/main/java/io/micronaut/build/services/DockerService.java
- src/site/asciidoc/examples/deploy.adoc
> Using docker-java client to push to remote registry instead of using Jib

- examples/java/micronaut-cli.yml
- examples/java/pom.xml
- pom.xml
- src/it/dockerfile-docker-netty/Dockerfile
- src/it/dockerfile-docker-netty/invoker.properties
- src/it/dockerfile-docker-netty/pom.xml
- src/it/dockerfile-docker-netty/src/main/java/io/micronaut/build/examples/Application.java
- src/it/dockerfile-docker-netty/src/main/java/io/micronaut/build/examples/greeter/Greeter.java
- src/it/dockerfile-docker-netty/src/main/resources/application.yml
- src/it/dockerfile-docker-netty/src/main/resources/logback.xml
- src/it/dockerfile-docker-netty/src/test/java/io/micronaut/build/examples/ApplicationTest.java
- src/it/dockerfile-docker-netty/verify.groovy
- src/main/java/io/micronaut/build/DockerfileMojo.java
- src/main/java/io/micronaut/build/jib/JibMicronautExtension.java
- src/main/java/io/micronaut/build/services/JibConfigurationService.java
- src/main/resources/dockerfiles/DockerfileOracleCloud
> Use explicit classpath for Oracle Cloud

- examples/java/pom.xml
- pom.xml
- src/it/deploy/invoker.properties
- src/it/package-docker-native/invoker.properties
- src/it/package-native-image/invoker.properties
- src/main/java/io/micronaut/build/DockerNativeMojo.java
> Check GraalVM profile activation

- src/it/dockerfile-docker-native-lambda/pom.xml
- src/main/java/io/micronaut/build/DockerNativeMojo.java
- src/main/resources/dockerfiles/DockerfileAwsCustomRuntime
> Use the exec.mainClass as AWS GraalVM dockerfile entrypoint

- src/it/dockerfile-docker-native-oracle-function/Dockerfile
- src/main/resources/dockerfiles/DockerfileNativeOracleCloud
Also see https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/240 and https://github.com/micronaut-projects/micronaut-starter/pull/895
> Oracle cloud function native image fixes

- .github/workflows/windows-ci.yml
- pom.xml
- src/it/dockerfile-docker-native-distroless/Dockerfile
- src/it/dockerfile-docker-native-distroless/pom.xml
- src/it/dockerfile-docker-native-lambda/Dockerfile
- src/it/dockerfile-docker-native-lambda/pom.xml
- src/it/dockerfile-docker-native-netty/Dockerfile
- src/it/dockerfile-docker-native-netty/pom.xml
- src/it/dockerfile-docker-native-oracle-function/Dockerfile
- src/it/dockerfile-docker-native-oracle-function/pom.xml
- src/it/dockerfile-docker-native-static/Dockerfile
- src/it/dockerfile-docker-native-static/pom.xml
- src/it/package-docker-native-distroless/pom.xml
- src/it/package-docker-native-static/Dockerfile
- src/it/package-docker-native-static/pom.xml
- src/it/package-docker-native/pom.xml
- src/it/package-jar/src/test/java/io/micronaut/build/examples/ApplicationTest.java
- src/it/package-native-image/invoker.properties
- src/it/package-native-image/pom.xml
- src/it/package-native-image/src/main/resources/logback.xml
- src/it/package-native-image/src/test/java/io/micronaut/build/examples/ApplicationTest.java
- src/it/package-native-image/verify.groovy
- src/main/java/io/micronaut/build/AbstractDockerMojo.java
- src/main/resources/META-INF/plexus/components.xml
- src/main/resources/dockerfiles/DockerfileNativeStatic
- src/site/asciidoc/examples/package.adoc
Fixes #232
Leaving it as a draft for now...
> Upgrade plugin to GraalVM 21.3.0 and official GraalVM Maven plugin

- src/it/dockerfile-docker-native-distroless/Dockerfile
- src/it/dockerfile-docker-native-netty/Dockerfile
- src/it/dockerfile-docker-native-oracle-function/Dockerfile
- src/it/dockerfile-docker-native-static/Dockerfile
- src/it/package-docker-native-static/Dockerfile
- src/main/java/io/micronaut/build/AbstractDockerMojo.java
- src/main/resources/dockerfiles/DockerfileNative
- src/main/resources/dockerfiles/DockerfileNativeDistroless
- src/main/resources/dockerfiles/DockerfileNativeOracleCloud
- src/main/resources/dockerfiles/DockerfileNativeStatic
> Use GraalVM slim image

- src/main/java/io/micronaut/build/AbstractDockerMojo.java
- src/main/java/io/micronaut/build/DockerNativeMojo.java
> Support JDK 17 for Docker packaging

- src/main/java/io/micronaut/build/RunMojo.java
> Allow watches on the target directory

- .github/workflows/sonarqube.yml
- README.md
- config/checkstyle/checkstyle.xml
- config/checkstyle/suppressions.xml
- config/spotless.license.java
- pom.xml
- src/main/java/io/micronaut/build/AbstractDockerMojo.java
- src/main/java/io/micronaut/build/DockerBuildStrategy.java
- src/main/java/io/micronaut/build/DockerMojo.java
- src/main/java/io/micronaut/build/DockerNativeMojo.java
- src/main/java/io/micronaut/build/DockerPushMojo.java
- src/main/java/io/micronaut/build/DockerfileMojo.java
- src/main/java/io/micronaut/build/GraalVMResourcesMojo.java
- src/main/java/io/micronaut/build/MicronautRuntime.java
- src/main/java/io/micronaut/build/Packaging.java
- src/main/java/io/micronaut/build/RunMojo.java
- src/main/java/io/micronaut/build/aot/AbstractMicronautAotCliMojo.java
- src/main/java/io/micronaut/build/aot/AbstractMicronautAotMojo.java
- src/main/java/io/micronaut/build/aot/AotAnalysisMojo.java
- src/main/java/io/micronaut/build/aot/AotRuntime.java
- src/main/java/io/micronaut/build/aot/AotSampleMojo.java
- src/main/java/io/micronaut/build/aot/Constants.java
- src/main/java/io/micronaut/build/jib/JibMicronautExtension.java
- src/main/java/io/micronaut/build/services/ApplicationConfigurationService.java
- src/main/java/io/micronaut/build/services/CompilerService.java
- src/main/java/io/micronaut/build/services/DockerService.java
- src/main/java/io/micronaut/build/services/ExecutorService.java
- src/main/java/io/micronaut/build/services/JibConfigurationService.java
> Add Checkstyle, JaCoCo, Spotless and Sonar to the build

- src/main/java/io/micronaut/build/AbstractDockerMojo.java
- src/main/java/io/micronaut/build/DockerMojo.java
- src/main/java/io/micronaut/build/DockerPushMojo.java
- src/main/java/io/micronaut/build/GraalVMResourcesMojo.java
- src/main/java/io/micronaut/build/RunMojo.java
- src/main/java/io/micronaut/build/aot/AotAnalysisMojo.java
- src/main/java/io/micronaut/build/aot/Constants.java
- src/main/java/io/micronaut/build/services/CompilerService.java
- src/main/java/io/micronaut/build/services/DockerService.java
> Fix some Sonar issues

- .github/workflows/graalvm.yml
- .github/workflows/snapshot.yml
- pom.xml
- src/it/dockerfile-docker-oracle-function/Dockerfile
- src/it/dockerfile-docker-oracle-function/Dockerfile.java8
- src/it/dockerfile-docker-oracle-function/verify.groovy
- src/it/package native image aot/verify.groovy
> GraalVM workflow

- src/main/java/io/micronaut/build/AbstractDockerMojo.java
- src/main/java/io/micronaut/build/DockerNativeMojo.java
- src/main/java/io/micronaut/build/DockerfileMojo.java
- src/main/resources/dockerfiles/DockerfileAwsCustomRuntime
- src/site/asciidoc/examples/package.adoc
> Make the GraalVM architecture a variable that is automatically detected

- .github/workflows/graalvm.yml
- .github/workflows/windows-ci.yml
- examples/java/pom.xml
- src/it/dockerfile-docker-native-distroless/Dockerfile
- src/it/dockerfile-docker-native-distroless/pom.xml
- src/it/dockerfile-docker-native-lambda/Dockerfile
- src/it/dockerfile-docker-native-lambda/pom.xml
- src/it/dockerfile-docker-native-netty/Dockerfile
- src/it/dockerfile-docker-native-netty/pom.xml
- src/it/dockerfile-docker-native-oracle-function/Dockerfile
- src/it/dockerfile-docker-native-oracle-function/pom.xml
- src/it/dockerfile-docker-native-static/Dockerfile
- src/it/dockerfile-docker-native-static/pom.xml
- src/it/package native image aot/pom.xml
- src/it/package-docker-native-distroless/pom.xml
- src/it/package-docker-native-static/Dockerfile
- src/it/package-docker-native-static/pom.xml
- src/it/package-docker-native/pom.xml
- src/it/package-native-image-aot/pom.xml
- src/it/package-native-image/pom.xml
- src/main/java/io/micronaut/build/DockerfileMojo.java
- src/main/resources/dockerfiles/DockerfileNativeStatic
This requires Micronaut core to upgrade to 22.1.0 too.
> Upgrade to GraalVM 22.1.0

- src/it/dockerfile-docker-native-distroless/Dockerfile
- src/it/dockerfile-docker-native-netty/Dockerfile
- src/it/dockerfile-docker-native-oracle-function/Dockerfile
- src/it/dockerfile-docker-native-static/Dockerfile
- src/it/package-docker-native-static/Dockerfile
- src/main/java/io/micronaut/build/AbstractDockerMojo.java
> Use Oracle Linux 7

- pom.xml
- src/it/package-docker-native-different-parent-version/invoker.properties
- src/it/package-docker-native-different-parent-version/pom.xml
- src/it/package-docker-native-different-parent-version/src/main/java/io/micronaut/build/examples/Application.java
- src/it/package-docker-native-different-parent-version/src/main/java/io/micronaut/build/examples/greeter/Greeter.java
- src/it/package-docker-native-different-parent-version/src/main/resources/application.yml
- src/it/package-docker-native-different-parent-version/src/main/resources/logback.xml
- src/it/package-docker-native-different-parent-version/src/test/java/io/micronaut/build/examples/ApplicationTest.java
- src/it/package-docker-native-different-parent-version/verify.groovy
- src/main/java/io/micronaut/build/DockerNativeMojo.java
> Fail the build if micronaut-parent and micronaut.version are different.

- pom.xml
- src/main/java/io/micronaut/build/RunMojo.java
- src/main/java/io/micronaut/build/testresources/AbstractTestResourcesMojo.java
- src/main/java/io/micronaut/build/testresources/MicronautStartTestResourcesServerMojo.java
- src/main/java/io/micronaut/build/testresources/MicronautStopTestResourcesServerMojo.java
- src/main/java/io/micronaut/build/testresources/TestResourcesLifecycleExtension.java
- src/main/resources/META-INF/plexus/components.xml
See individual commits for details.
> Handle lifecycle of the test resources service

- examples/java/pom.xml
- graalvm-ce-dev/Dockerfile.ol7-java11-dev
- graalvm-ce-dev/gu-wrapper.sh
- src/it/dockerfile-docker-native-distroless/Dockerfile
- src/it/dockerfile-docker-native-lambda/Dockerfile.aarch64
- src/it/dockerfile-docker-native-lambda/Dockerfile.amd64
- src/it/dockerfile-docker-native-lambda/verify.groovy
- src/it/dockerfile-docker-native-netty/Dockerfile
- src/it/dockerfile-docker-native-oracle-function/Dockerfile
- src/it/dockerfile-docker-native-static/Dockerfile
- src/it/package native image aot/pom.xml
- src/it/package-native-image-aot/pom.xml
- src/it/package-native-image/pom.xml
- src/main/resources/dockerfiles/DockerfileNative
- src/main/resources/dockerfiles/DockerfileNativeDistroless
- src/main/resources/dockerfiles/DockerfileNativeOracleCloud
- src/main/resources/dockerfiles/DockerfileNativeStatic
Fixes #423
Creating this as draft, since some of the changes will need to be removed in favour of a change in the parent POM, once we verify here it works.
> Make the build work with GraalVM 22.2

- pom.xml
- src/it/dockerfile-docker-oracle-function/Dockerfile
- src/main/java/io/micronaut/build/jib/JibMicronautExtension.java
Fix for java path entry point to new Oracle fdk image.
Tested via following these steps. https://guides.micronaut.io/latest/micronaut-oracle-function-maven-java.html 
Works as expected.
> Fix for issue https://github.com/micronaut-projects/micronaut-maven-plugin/issues/447

- src/main/resources/cracScripts/checkpoint.sh
- src/site/asciidoc/examples/package.adoc
And update the PID so the java app runs on PID 600, so we have less chance of collisions
Analog of https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/564
> Document running CRaC images

- src/it/dockerfile-docker-native-oracle-function/Dockerfile
- src/it/dockerfile-docker-oracle-function/Dockerfile
- src/main/java/io/micronaut/maven/jib/JibMicronautExtension.java
- src/main/resources/dockerfiles/DockerfileNativeOracleCloud
> Support OCI Function Java 17

- src/it/dockerfile-docker-native-lambda/Dockerfile.aarch64
- src/it/dockerfile-docker-native-lambda/Dockerfile.amd64
- src/it/dockerfile-docker-native-oracle-function/Dockerfile
- src/main/resources/dockerfiles/DockerfileAwsCustomRuntime
- src/main/resources/dockerfiles/DockerfileNativeOracleCloud
To match what the Gradle plugin generates.
@melix please, ping me once you make changes in the Gradle side so that I keep those here in sync
> Update Dockerfile templates

- micronaut-maven-integration-tests/src/it/dockerfile-docker-crac/pom.xml
- micronaut-maven-integration-tests/src/it/package-docker-crac-aot/pom.xml
- micronaut-maven-integration-tests/src/it/package-docker-crac/pom.xml
> Add runtime dependency on jackson-databind to get a JsonConfiguration bean

- micronaut-maven-plugin/src/main/java/io/micronaut/maven/AbstractDockerMojo.java
- micronaut-maven-plugin/src/main/java/io/micronaut/maven/DockerCracMojo.java
- micronaut-maven-plugin/src/main/java/io/micronaut/maven/DockerMojo.java
- micronaut-maven-plugin/src/main/java/io/micronaut/maven/DockerNativeMojo.java
> Support network mode parameter for Docker builds

- micronaut-maven-integration-tests/src/it/package-docker-down/invoker.properties
- micronaut-maven-integration-tests/src/it/package-docker-down/pom.xml
- micronaut-maven-integration-tests/src/it/package-docker-down/src/main/java/io/micronaut/build/examples/Application.java
- micronaut-maven-integration-tests/src/it/package-docker-down/verify.groovy
- micronaut-maven-integration-tests/src/it/package-docker-native-docker-down/invoker.properties
- micronaut-maven-integration-tests/src/it/package-docker-native-docker-down/pom.xml
- micronaut-maven-integration-tests/src/it/package-docker-native-docker-down/src/main/java/io/micronaut/build/examples/Application.java
- micronaut-maven-integration-tests/src/it/package-docker-native-docker-down/verify.groovy
- micronaut-maven-plugin/src/main/java/io/micronaut/maven/services/DockerService.java
> Verify that the Docker daemon is running

- micronaut-maven-integration-tests/src/it/dockerfile-docker-native-distroless/Dockerfile
- micronaut-maven-integration-tests/src/it/dockerfile-docker-native-lambda/Dockerfile.aarch64
- micronaut-maven-integration-tests/src/it/dockerfile-docker-native-lambda/Dockerfile.amd64
- micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty-custom-ol/Dockerfile
- micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty/Dockerfile
- micronaut-maven-integration-tests/src/it/dockerfile-docker-native-oracle-function/Dockerfile
- micronaut-maven-integration-tests/src/it/dockerfile-docker-native-static/Dockerfile
- micronaut-maven-plugin/src/main/resources/dockerfiles/DockerfileAwsCustomRuntime
- micronaut-maven-plugin/src/main/resources/dockerfiles/DockerfileNative
- micronaut-maven-plugin/src/main/resources/dockerfiles/DockerfileNativeDistroless
- micronaut-maven-plugin/src/main/resources/dockerfiles/DockerfileNativeOracleCloud
- micronaut-maven-plugin/src/main/resources/dockerfiles/DockerfileNativeStatic
> Remove `USE_NATIVE_IMAGE_JAVA_PLATFORM_MODULE_SYSTEM`

- micronaut-maven-integration-tests/src/it/run-aot-jvmargs/aot.properties
- micronaut-maven-integration-tests/src/it/run-aot-jvmargs/invoker.properties
- micronaut-maven-integration-tests/src/it/run-aot-jvmargs/pom.xml
- micronaut-maven-integration-tests/src/it/run-aot-jvmargs/src/main/java/io/micronaut/build/examples/RunCommand.java
- micronaut-maven-integration-tests/src/it/run-aot-jvmargs/src/main/resources/application.yml
- micronaut-maven-integration-tests/src/it/run-aot-jvmargs/src/main/resources/logback.xml
- micronaut-maven-integration-tests/src/it/run-aot-jvmargs/src/test/java/io/micronaut/build/examples/RunCommandTest.java
- micronaut-maven-integration-tests/src/it/run-aot-jvmargs/verify.groovy
- micronaut-maven-plugin/src/main/java/io/micronaut/maven/RunMojo.java
- micronaut-maven-plugin/src/main/java/io/micronaut/maven/aot/AbstractMicronautAotCliMojo.java
> Support passing JVM arguments to the AOT process

- micronaut-maven-integration-tests/src/it/dockerfile-docker-native-lambda/Dockerfile.aarch64
- micronaut-maven-integration-tests/src/it/dockerfile-docker-native-lambda/Dockerfile.amd64
- micronaut-maven-plugin/src/main/resources/dockerfiles/DockerfileAwsCustomRuntime
- micronaut-maven-plugin/src/site/asciidoc/examples/package.adoc
This was an unwanted side-effect in #623
Fixes #798
> Rollback to Amazon Linux 2

- micronaut-maven-enforcer-rules/src/main/java/io/micronaut/maven/enforcer/CheckSnakeYaml.java
- micronaut-maven-integration-tests/pom.xml
- micronaut-maven-integration-tests/src/it/dockerfile-docker-native-lambda/Dockerfile.aarch64
- micronaut-maven-integration-tests/src/it/dockerfile-docker-native-lambda/Dockerfile.amd64
- micronaut-maven-integration-tests/src/it/package-docker-native-lambda/invoker.properties
- micronaut-maven-integration-tests/src/it/package-docker-native-lambda/pom.xml
- micronaut-maven-integration-tests/src/it/package-docker-native-lambda/src/main/java/io/micronaut/build/examples/Application.java
- micronaut-maven-integration-tests/src/it/package-docker-native-lambda/src/main/java/io/micronaut/build/examples/greeter/Greeter.java
- micronaut-maven-integration-tests/src/it/package-docker-native-lambda/src/main/resources/application.yml
- micronaut-maven-integration-tests/src/it/package-docker-native-lambda/src/main/resources/logback.xml
- micronaut-maven-integration-tests/src/it/package-docker-native-lambda/src/test/java/io/micronaut/build/examples/ApplicationTest.java
- micronaut-maven-integration-tests/src/it/package-docker-native-lambda/verify.groovy
- micronaut-maven-plugin/src/main/java/io/micronaut/maven/DockerNativeMojo.java
- micronaut-maven-plugin/src/main/java/io/micronaut/maven/DockerfileMojo.java
- micronaut-maven-plugin/src/main/resources/dockerfiles/DockerfileAwsCustomRuntime
Fixes: #798
Closes: #804
Closes: #805
> Fix AWS Lambda custom runtime generation

- micronaut-maven-plugin/src/main/java/io/micronaut/maven/DockerPushMojo.java
This PR improves pushing to Docker registries by reading authentication credentials from either well known credential helpers, or the default Docker config as a last resort.
Therefore, it provides seamless support for use cases where the user has run `docker login` locally.
> Improve Docker push

- micronaut-maven-plugin/src/main/java/io/micronaut/maven/RunMojo.java
- micronaut-maven-plugin/src/main/java/io/micronaut/maven/testresources/TestResourcesHelper.java
This commit fixes the watch mode for several issues, which are best highlighted by a long application startup:
- there can now only be a single compilation request at a time. Previously, if compilation took more time than the time it takes to get another watch change request, 2 compilations could happen concurrently
- application restarts are queued. If an application is requested to be restarted, we have to wait for the previous process to be killed before starting the new version. We do this by using a lock. We can safely discard restart requests if there is already a request in queue, because it would use the latest version in any case
- the test resources service keep alive file should not use the session start time, because that time changes when using watch mode. This was trigerring …
> Fix race conditions in watch mode

- micronaut-maven-plugin/src/main/java/io/micronaut/maven/RunMojo.java
I got java.nio.file.NoSuchFileException exception and I added a condition to check if the file exists first to fix this.
> Fix maven plugin Windows issue
